In [10]:
!uv pip install -q --system numba-cuda==0.4.0

In [11]:
from numba import config
config.CUDA_ENABLE_PYNVJITLINK = 1

# Numba Lab

Now it's your turn!

Your challenge is to implement Fizz Buzz in CUDA Python with Numba and calculate all instances of `Fizz`, `Buzz`, and `Fizz Buzz` for the numbers between `1` and `50_000_000`.

Before you begin, if you're running this notebook in Google Colab, please turn off autocompletion by going to the settings gear in the top right -> Editor -> Uncheck "Automatically trigger code completions".

In [12]:
import numpy as np
from numba import cuda

**1. Create the input data array.** Try using `np.arange`.

In [13]:
data = np.arange(1,50_000_001)
data

array([       1,        2,        3, ..., 49999998, 49999999, 50000000])

**2. Create the output data array.**

In [14]:
output = np.zeros_like(data)
output

array([0, 0, 0, ..., 0, 0, 0])

**3. Calculate the number of threads and blocks.**

In [15]:
threads = 128
blocks = data.shape[0] // threads + 1

**4. Create the kernel.** _Tip: Our output array must be numeric so try using the values `1`, `2`, and `3` to represent `Fizz`, `Buzz`, and `Fizz Buzz`._

In [28]:
@cuda.jit
def fizz_buzz(input_array, output_array):
    i = cuda.grid(1)
    if input_array[i] % 3 == 0:
      output_array[i] = 1
    if input_array[i] % 5 == 0:
      output_array[i] = 2
    if input_array[i] % (3 * 5) == 0:
      output_array[i] = 3

**5. Run our kernel.**

In [29]:
%%time
fizz_buzz[blocks, threads](data, output)
output[:15]

/usr/local/lib/python3.11/dist-packages/numba_cuda/numba/cuda/cudadrv/devicearray.py:893: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))


CPU times: user 430 ms, sys: 3.06 ms, total: 433 ms
Wall time: 434 ms


array([0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 0, 0, 3])

**Extra Credit 6. Calculate the highest instance of `Fizz`.**

In [46]:
idx = (50_000_000 // 3) * 3
output[idx-1]

1